version: "3.7"

services:
  backend:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
  db:
    image: mysql
    expose:
      - "3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: "mysuperrootpasswd"
      MYSQL_DATABASE: "image_test"
      MYSQL_USER: "scripulya"
      MYSQL_PASSWORD: "scripulya_pass"
    volumes:
      - "./db:/var/lib/mysql"



